### ISSUE TITLE
can you make a java library out of it? like a maven project with pom.xml and such. 

### ISSUE THREAD

**Issue by pointbazaar** [maste150hhu/MovingPoint#1]
it would really help for people trying to use your project. then they can just add it as a dependency.

**Comment by MarcoSteinke** [comment]
Added to TODO's.

**Comment by MarcoSteinke** [comment]
At the current state of the project it is not possible to create a maven project.

**Comment by MarcoSteinke** [comment]
MP is now a Maven Project
